[package]
name = "rust_timer"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.7", package = "gtk4", features = ["v4_2"] }
glib-2-0-sys = { version = "0.18", package = "glib", features = ["v2_66"] }


# /usr/include/glib-2.0/glib/glib.h
# /usr/include/glib-2.0/glib/gmacros.h
